// ---------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Visual Studio Protobuf Language Service.
//     https://visualstudiogallery.msdn.microsoft.com/4bc0f38c-b058-4e05-ae38-155e053c19c5
//
//     Protobuf-net from Marc Gravell is needed to use this code.
//     https://code.google.com/p/protobuf-net/
//
//     This code was generated by the help of the google protoc.exe (protobuf compiler) version 2.6.1
//     and protobuf-net version 2.0.0.668
//
//     Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

// generated from test.proto

// Code generated with the following options:
//  DataContract
//  Asynchronous
//  ClientProxy
//  FixCase
//  TreatObsoleteAsError

namespace projectname
{
    [global::System.Serializable]
    [global::ProtoBuf.ProtoContract(Name = @"simpleMessage")]
    [global::System.Runtime.Serialization.DataContract(Name = @"simpleMessage")]
    public partial class SimpleMessage : global::ProtoBuf.IExtensible
    {
        public SimpleMessage() { }

        private int _i1Int32Test;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"i1_int32_test", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.Runtime.Serialization.DataMember(Name = @"i1_int32_test", Order = 1, IsRequired = true)]
        public int I1Int32Test
        {
            get { return _i1Int32Test; }
            set { _i1Int32Test = value; }
        }

        private int _i2 = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"i2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        [global::System.Runtime.Serialization.DataMember(Name = @"i2", Order = 2, IsRequired = false)]
        public int I2
        {
            get { return _i2; }
            set { _i2 = value; }
        }

        private string _s1String = "";
        [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name = @"s1_string", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        [global::System.Runtime.Serialization.DataMember(Name = @"s1_string", Order = 12, IsRequired = false)]
        public string S1String
        {
            get { return _s1String; }
            set { _s1String = value; }
        }

        private readonly global::System.Collections.Generic.List<int> _i33d = new global::System.Collections.Generic.List<int>();
        [global::ProtoBuf.ProtoMember(3, Name = @"i3_3d", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.Runtime.Serialization.DataMember(Name = @"i3_3d", Order = 3, IsRequired = false)]
        public global::System.Collections.Generic.List<int> I33d
        {
            get { return _i33d; }
        }

        private SimpleEnum _type = SimpleEnum.Zwei;
        [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(SimpleEnum.Zwei)]
        [global::System.Runtime.Serialization.DataMember(Name = @"type", Order = 44, IsRequired = false)]
        public SimpleEnum Type
        {
            get { return _type; }
            set { _type = value; }
        }

        private SimpleEnum _type2 = SimpleEnum.Zwei;
        [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name = @"type2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(SimpleEnum.Zwei)]
        [global::System.Runtime.Serialization.DataMember(Name = @"type2", Order = 45, IsRequired = false)]
        public SimpleEnum Type2
        {
            get { return _type2; }
            set { _type2 = value; }
        }

        private VerySimple _msg = null;
        [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name = @"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        [global::System.Runtime.Serialization.DataMember(Name = @"msg", Order = 33, IsRequired = false)]
        public VerySimple Msg
        {
            get { return _msg; }
            set { _msg = value; }
        }

        private readonly global::System.Collections.Generic.List<VerySimple> _list = new global::System.Collections.Generic.List<VerySimple>();
        [global::ProtoBuf.ProtoMember(34, Name = @"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.Runtime.Serialization.DataMember(Name = @"list", Order = 34, IsRequired = false)]
        public global::System.Collections.Generic.List<VerySimple> List
        {
            get { return _list; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }

    [global::System.Serializable]
    [global::ProtoBuf.ProtoContract(Name = @"verySimple")]
    [global::System.Runtime.Serialization.DataContract(Name = @"verySimple")]
    public partial class VerySimple : global::ProtoBuf.IExtensible
    {
        public VerySimple() { }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }

    [global::ProtoBuf.ProtoContract(Name = @"simpleEnum")]
    [global::System.Runtime.Serialization.DataContract(Name = @"simpleEnum")]
    public enum SimpleEnum
    {
        [global::ProtoBuf.ProtoEnum(Name = @"eins", Value = 1)]
        [global::System.Runtime.Serialization.EnumMember(Value = @"eins")]
        Eins = 1,

        [global::ProtoBuf.ProtoEnum(Name = @"zwei", Value = 2)]
        [global::System.Runtime.Serialization.EnumMember(Value = @"zwei")]
        Zwei = 2,
    }

    [global::System.ServiceModel.ServiceContract(Name = @"simpleService1")]
    public interface ISimpleService1
    {
        [global::System.ServiceModel.OperationContract(Name = @"s1")]
        [global::ProtoBuf.ServiceModel.ProtoBehavior]
        SimpleMessage S1(SimpleMessage request);

        [global::System.ServiceModel.OperationContract(AsyncPattern = true, Name = @"S1")]
        global::System.IAsyncResult BeginS1(SimpleMessage request, global::System.AsyncCallback callback, object state);
        SimpleMessage EndS1(global::System.IAsyncResult ar);

        [global::System.ServiceModel.OperationContract(Name = @"s11")]
        [global::ProtoBuf.ServiceModel.ProtoBehavior]
        SimpleMessage S11(SimpleMessage request);

        [global::System.ServiceModel.OperationContract(AsyncPattern = true, Name = @"S11")]
        global::System.IAsyncResult BeginS11(SimpleMessage request, global::System.AsyncCallback callback, object state);
        SimpleMessage EndS11(global::System.IAsyncResult ar);
    }

    public partial class S1CompletedEventArgs : global::System.ComponentModel.AsyncCompletedEventArgs
    {
        private readonly object[] results;

        public S1CompletedEventArgs(object[] results, global::System.Exception exception, bool cancelled, object userState)
            : base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public SimpleMessage Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return (SimpleMessage)(this.results[0]);
            }
        }
    }

    public partial class S11CompletedEventArgs : global::System.ComponentModel.AsyncCompletedEventArgs
    {
        private readonly object[] results;

        public S11CompletedEventArgs(object[] results, global::System.Exception exception, bool cancelled, object userState)
            : base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public SimpleMessage Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return (SimpleMessage)(this.results[0]);
            }
        }
    }

    [global::System.ServiceModel.ServiceContract(Name = @"simpleService2")]
    public interface ISimpleService2
    {
        [global::System.ServiceModel.OperationContract(Name = @"s2")]
        [global::ProtoBuf.ServiceModel.ProtoBehavior]
        SimpleMessage S2(SimpleMessage request);

        [global::System.ServiceModel.OperationContract(AsyncPattern = true, Name = @"S2")]
        global::System.IAsyncResult BeginS2(SimpleMessage request, global::System.AsyncCallback callback, object state);
        SimpleMessage EndS2(global::System.IAsyncResult ar);
    }

    public partial class S2CompletedEventArgs : global::System.ComponentModel.AsyncCompletedEventArgs
    {
        private readonly object[] results;
        public S2CompletedEventArgs(object[] results, global::System.Exception exception, bool cancelled, object userState)
            : base(exception, cancelled, userState)
        {
            this.results = results;
        }
        public SimpleMessage Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return (SimpleMessage)(this.results[0]);
            }
        }
    }
}