// ---------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Visual Studio Protobuf Language Service.
//     https://visualstudiogallery.msdn.microsoft.com/4bc0f38c-b058-4e05-ae38-155e053c19c5
//
//     Protobuf-net from Marc Gravell is needed to use this code.
//     https://code.google.com/p/protobuf-net/
//
//     This code was generated by the help of the google protoc.exe (protobuf compiler) version 2.6.1
//     and protobuf-net version 2.0.0.668
//
//     Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

// generated from test.proto

// Code generated with the following options:
//  DataContract
//  Asynchronous
//  ClientProxy
//  FixCase
//  TreatObsoleteAsError

namespace projectname
{
    [global::System.Serializable]
    [global::ProtoBuf.ProtoContract(Name = @"simpleMessage1")]
    [global::System.Runtime.Serialization.DataContract(Name = @"simpleMessage1")]
    public partial class SimpleMessage1 : global::ProtoBuf.IExtensible
    {
        public SimpleMessage1() { }

        private int _i1Int32Test;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"i1_int32_test", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.Runtime.Serialization.DataMember(Name = @"i1_int32_test", Order = 1, IsRequired = true)]
        public int I1Int32Test
        {
            get { return _i1Int32Test; }
            set { _i1Int32Test = value; }
        }

        private int _i2 = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"i2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        [global::System.Runtime.Serialization.DataMember(Name = @"i2", Order = 2, IsRequired = false)]
        public int I2
        {
            get { return _i2; }
            set { _i2 = value; }
        }

        private string _s1String = "";
        [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name = @"s1_string", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        [global::System.Runtime.Serialization.DataMember(Name = @"s1_string", Order = 12, IsRequired = false)]
        public string S1String
        {
            get { return _s1String; }
            set { _s1String = value; }
        }

        private readonly global::System.Collections.Generic.List<int> _i33d = new global::System.Collections.Generic.List<int>();
        [global::ProtoBuf.ProtoMember(3, Name = @"i3_3d", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.Runtime.Serialization.DataMember(Name = @"i3_3d", Order = 3, IsRequired = false)]
        public global::System.Collections.Generic.List<int> I33d
        {
            get { return _i33d; }
        }

        private SimpleEnum _type = SimpleEnum.Zwei;
        [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(SimpleEnum.Zwei)]
        [global::System.Runtime.Serialization.DataMember(Name = @"type", Order = 44, IsRequired = false)]
        public SimpleEnum Type
        {
            get { return _type; }
            set { _type = value; }
        }

        private SimpleEnum _type2 = SimpleEnum.Zwei;
        [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name = @"type2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(SimpleEnum.Zwei)]
        [global::System.Runtime.Serialization.DataMember(Name = @"type2", Order = 45, IsRequired = false)]
        public SimpleEnum Type2
        {
            get { return _type2; }
            set { _type2 = value; }
        }

        private VerySimple _msg = null;
        [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name = @"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        [global::System.Runtime.Serialization.DataMember(Name = @"msg", Order = 33, IsRequired = false)]
        public VerySimple Msg
        {
            get { return _msg; }
            set { _msg = value; }
        }

        private readonly global::System.Collections.Generic.List<VerySimple> _list = new global::System.Collections.Generic.List<VerySimple>();
        [global::ProtoBuf.ProtoMember(34, Name = @"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.Runtime.Serialization.DataMember(Name = @"list", Order = 34, IsRequired = false)]
        public global::System.Collections.Generic.List<VerySimple> List
        {
            get { return _list; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }

    [global::System.Serializable]
    [global::ProtoBuf.ProtoContract(Name = @"verySimple")]
    [global::System.Runtime.Serialization.DataContract(Name = @"verySimple")]
    public partial class VerySimple : global::ProtoBuf.IExtensible
    {
        public VerySimple() { }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }

    [global::System.Serializable]
    [global::ProtoBuf.ProtoContract(Name = @"inMsg1")]
    [global::System.Runtime.Serialization.DataContract(Name = @"inMsg1")]
    public partial class InMsg1 : global::ProtoBuf.IExtensible
    {
        public InMsg1() { }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }

    [global::System.Serializable]
    [global::ProtoBuf.ProtoContract(Name = @"outMsg2")]
    [global::System.Runtime.Serialization.DataContract(Name = @"outMsg2")]
    public partial class OutMsg2 : global::ProtoBuf.IExtensible
    {
        public OutMsg2() { }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
        }
    }

    [global::ProtoBuf.ProtoContract(Name = @"simpleEnum")]
    [global::System.Runtime.Serialization.DataContract(Name = @"simpleEnum")]
    public enum SimpleEnum
    {
        [global::ProtoBuf.ProtoEnum(Name = @"eins", Value = 1)]
        [global::System.Runtime.Serialization.EnumMember(Value = @"eins")]
        Eins = 1,

        [global::ProtoBuf.ProtoEnum(Name = @"zwei", Value = 2)]
        [global::System.Runtime.Serialization.EnumMember(Value = @"zwei")]
        Zwei = 2,
    }

    [global::System.ServiceModel.ServiceContract(Name = @"simpleService3")]
    public interface ISimpleService3
    {
        [global::System.ServiceModel.OperationContract(Name = @"s21")]
        [global::ProtoBuf.ServiceModel.ProtoBehavior]
        OutMsg2 S21(InMsg1 request);

        [global::System.ServiceModel.OperationContract(AsyncPattern = true, Name = @"S21")]
        global::System.IAsyncResult BeginS21(InMsg1 request, global::System.AsyncCallback callback, object state);
        OutMsg2 EndS21(global::System.IAsyncResult ar);

        [global::System.ServiceModel.OperationContract(Name = @"s211")]
        [global::ProtoBuf.ServiceModel.ProtoBehavior]
        SimpleMessage1 S211(SimpleMessage1 request);

        [global::System.ServiceModel.OperationContract(AsyncPattern = true, Name = @"S211")]
        global::System.IAsyncResult BeginS211(SimpleMessage1 request, global::System.AsyncCallback callback, object state);
        SimpleMessage1 EndS211(global::System.IAsyncResult ar);
    }

    public partial class S21CompletedEventArgs : global::System.ComponentModel.AsyncCompletedEventArgs
    {
        private readonly object[] results;

        public S21CompletedEventArgs(object[] results, global::System.Exception exception, bool cancelled, object userState)
            : base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public OutMsg2 Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return (OutMsg2)(this.results[0]);
            }
        }
    }

    public partial class S211CompletedEventArgs : global::System.ComponentModel.AsyncCompletedEventArgs
    {
        private readonly object[] results;

        public S211CompletedEventArgs(object[] results, global::System.Exception exception, bool cancelled, object userState)
            : base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public SimpleMessage1 Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return (SimpleMessage1)(this.results[0]);
            }
        }
    }

    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class SimpleService3Client : global::System.ServiceModel.ClientBase<ISimpleService3>, ISimpleService3
    {
        public SimpleService3Client()
        { }
        public SimpleService3Client(string endpointConfigurationName)
            : base(endpointConfigurationName)
        { }
        public SimpleService3Client(string endpointConfigurationName, string remoteAddress)
            : base(endpointConfigurationName, remoteAddress)
        { }
        public SimpleService3Client(string endpointConfigurationName, global::System.ServiceModel.EndpointAddress remoteAddress)
            : base(endpointConfigurationName, remoteAddress)
        { }
        public SimpleService3Client(global::System.ServiceModel.Channels.Binding binding, global::System.ServiceModel.EndpointAddress remoteAddress)
            : base(binding, remoteAddress)
        { }

        private BeginOperationDelegate onBeginS21Delegate;
        private EndOperationDelegate onEndS21Delegate;
        private global::System.Threading.SendOrPostCallback onS21CompletedDelegate;
        public event global::System.EventHandler<S21CompletedEventArgs> S21Completed;

        public OutMsg2 S21(InMsg1 request)
        {
            return base.Channel.S21(request);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.IAsyncResult BeginS21(InMsg1 request, global::System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginS21(request, callback, asyncState);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public OutMsg2 EndS21(global::System.IAsyncResult result)
        {
            return base.Channel.EndS21(result);
        }

        private global::System.IAsyncResult OnBeginS21(object[] inValues, global::System.AsyncCallback callback, object asyncState)
        {
            InMsg1 request = (InMsg1)(inValues[0]);
            return this.BeginS21(request, callback, asyncState);
        }

        private object[] OnEndS21(global::System.IAsyncResult result)
        {
            OutMsg2 retVal = this.EndS21(result);
            return new object[] { retVal };
        }

        private void OnS21Completed(object state)
        {
            if (this.S21Completed != null)
            {
                InvokeAsyncCompletedEventArgs e = (InvokeAsyncCompletedEventArgs)(state);
                this.S21Completed(this, new S21CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void S21Async(InMsg1 request)
        {
            this.S21Async(request, null);
        }

        public void S21Async(InMsg1 request, object userState)
        {
            if ((this.onBeginS21Delegate == null))
                this.onBeginS21Delegate = new BeginOperationDelegate(this.OnBeginS21);

            if ((this.onEndS21Delegate == null))
                this.onEndS21Delegate = new EndOperationDelegate(this.OnEndS21);

            if ((this.onS21CompletedDelegate == null))
                this.onS21CompletedDelegate = new global::System.Threading.SendOrPostCallback(this.OnS21Completed);

            base.InvokeAsync(this.onBeginS21Delegate,
                new object[] { request },
                this.onEndS21Delegate,
                this.onS21CompletedDelegate,
                userState);
        }


        private BeginOperationDelegate onBeginS211Delegate;
        private EndOperationDelegate onEndS211Delegate;
        private global::System.Threading.SendOrPostCallback onS211CompletedDelegate;
        public event global::System.EventHandler<S211CompletedEventArgs> S211Completed;

        public SimpleMessage1 S211(SimpleMessage1 request)
        {
            return base.Channel.S211(request);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.IAsyncResult BeginS211(SimpleMessage1 request, global::System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginS211(request, callback, asyncState);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public SimpleMessage1 EndS211(global::System.IAsyncResult result)
        {
            return base.Channel.EndS211(result);
        }

        private global::System.IAsyncResult OnBeginS211(object[] inValues, global::System.AsyncCallback callback, object asyncState)
        {
            SimpleMessage1 request = (SimpleMessage1)(inValues[0]);
            return this.BeginS211(request, callback, asyncState);
        }

        private object[] OnEndS211(global::System.IAsyncResult result)
        {
            SimpleMessage1 retVal = this.EndS211(result);
            return new object[] { retVal };
        }

        private void OnS211Completed(object state)
        {
            if (this.S211Completed != null)
            {
                InvokeAsyncCompletedEventArgs e = (InvokeAsyncCompletedEventArgs)(state);
                this.S211Completed(this, new S211CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void S211Async(SimpleMessage1 request)
        {
            this.S211Async(request, null);
        }

        public void S211Async(SimpleMessage1 request, object userState)
        {
            if ((this.onBeginS211Delegate == null))
                this.onBeginS211Delegate = new BeginOperationDelegate(this.OnBeginS211);

            if ((this.onEndS211Delegate == null))
                this.onEndS211Delegate = new EndOperationDelegate(this.OnEndS211);

            if ((this.onS211CompletedDelegate == null))
                this.onS211CompletedDelegate = new global::System.Threading.SendOrPostCallback(this.OnS211Completed);

            base.InvokeAsync(this.onBeginS211Delegate,
                new object[] { request },
                this.onEndS211Delegate,
                this.onS211CompletedDelegate,
                userState);
        }

    }

    [global::System.ServiceModel.ServiceContract(Name = @"simpleService4")]
    public interface ISimpleService4
    {
        [global::System.ServiceModel.OperationContract(Name = @"s22")]
        [global::ProtoBuf.ServiceModel.ProtoBehavior]
        SimpleMessage1 S22(SimpleMessage1 request);

        [global::System.ServiceModel.OperationContract(AsyncPattern = true, Name = @"S22")]
        global::System.IAsyncResult BeginS22(SimpleMessage1 request, global::System.AsyncCallback callback, object state);
        SimpleMessage1 EndS22(global::System.IAsyncResult ar);
    }

    public partial class S22CompletedEventArgs : global::System.ComponentModel.AsyncCompletedEventArgs
    {
        private readonly object[] results;

        public S22CompletedEventArgs(object[] results, global::System.Exception exception, bool cancelled, object userState)
            : base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public SimpleMessage1 Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return (SimpleMessage1)(this.results[0]);
            }
        }
    }

    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class SimpleService4Client : global::System.ServiceModel.ClientBase<ISimpleService4>, ISimpleService4
    {
        public SimpleService4Client()
        { }
        public SimpleService4Client(string endpointConfigurationName)
            : base(endpointConfigurationName)
        { }
        public SimpleService4Client(string endpointConfigurationName, string remoteAddress)
            : base(endpointConfigurationName, remoteAddress)
        { }
        public SimpleService4Client(string endpointConfigurationName, global::System.ServiceModel.EndpointAddress remoteAddress)
            : base(endpointConfigurationName, remoteAddress)
        { }
        public SimpleService4Client(global::System.ServiceModel.Channels.Binding binding, global::System.ServiceModel.EndpointAddress remoteAddress)
            : base(binding, remoteAddress)
        { }

        private BeginOperationDelegate onBeginS22Delegate;
        private EndOperationDelegate onEndS22Delegate;
        private global::System.Threading.SendOrPostCallback onS22CompletedDelegate;
        public event global::System.EventHandler<S22CompletedEventArgs> S22Completed;

        public SimpleMessage1 S22(SimpleMessage1 request)
        {
            return base.Channel.S22(request);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.IAsyncResult BeginS22(SimpleMessage1 request, global::System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginS22(request, callback, asyncState);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public SimpleMessage1 EndS22(global::System.IAsyncResult result)
        {
            return base.Channel.EndS22(result);
        }

        private global::System.IAsyncResult OnBeginS22(object[] inValues, global::System.AsyncCallback callback, object asyncState)
        {
            SimpleMessage1 request = (SimpleMessage1)(inValues[0]);
            return this.BeginS22(request, callback, asyncState);
        }

        private object[] OnEndS22(global::System.IAsyncResult result)
        {
            SimpleMessage1 retVal = this.EndS22(result);
            return new object[] { retVal };
        }

        private void OnS22Completed(object state)
        {
            if (this.S22Completed != null)
            {
                InvokeAsyncCompletedEventArgs e = (InvokeAsyncCompletedEventArgs)(state);
                this.S22Completed(this, new S22CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void S22Async(SimpleMessage1 request)
        {
            this.S22Async(request, null);
        }

        public void S22Async(SimpleMessage1 request, object userState)
        {
            if ((this.onBeginS22Delegate == null))
                this.onBeginS22Delegate = new BeginOperationDelegate(this.OnBeginS22);

            if ((this.onEndS22Delegate == null))
                this.onEndS22Delegate = new EndOperationDelegate(this.OnEndS22);

            if ((this.onS22CompletedDelegate == null))
                this.onS22CompletedDelegate = new global::System.Threading.SendOrPostCallback(this.OnS22Completed);

            base.InvokeAsync(this.onBeginS22Delegate,
                new object[] { request },
                this.onEndS22Delegate,
                this.onS22CompletedDelegate,
                userState);
        }

    }
}