// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

// Option: data-contract serialization ([DataContract]/[DataMember]) enabled
    
// Option: fix case enabled
    
// Generated from: Test.proto
namespace Test
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"simpleMessage")]
  [global::System.Runtime.Serialization.DataContract(Name=@"simpleMessage")]
  public partial class SimpleMessage : global::ProtoBuf.IExtensible
  {
    private int _i1Int32Test = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"i1_int32_test", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    [global::System.Runtime.Serialization.DataMember(Name=@"i1_int32_test", Order = 1, IsRequired = true)]
    
    public int I1Int32Test
    {
      get { return _i1Int32Test; }
      set { _i1Int32Test = value; }
    }
    private int _i2 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"i2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    [global::System.Runtime.Serialization.DataMember(Name=@"i2", Order = 2, IsRequired = false)]
    
    public int I2
    {
      get { return _i2; }
      set { _i2 = value; }
    }
    private string _s1String = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"s1_string", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    [global::System.Runtime.Serialization.DataMember(Name=@"s1_string", Order = 12, IsRequired = false)]
    
    public string S1String
    {
      get { return _s1String; }
      set { _s1String = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _i33d = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"i3_3d", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.Runtime.Serialization.DataMember(Name=@"i3_3d", Order = 3, IsRequired = false)]
    
    public global::System.Collections.Generic.List<int> I33d
    {
      get { return _i33d; }
    }
  
    private SimpleEnum _type = SimpleEnum.Zwei;
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(SimpleEnum.Zwei)]
    [global::System.Runtime.Serialization.DataMember(Name=@"type", Order = 44, IsRequired = false)]
    
    public SimpleEnum Type
    {
      get { return _type; }
      set { _type = value; }
    }
    private SimpleEnum _type2 = SimpleEnum.Zwei;
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"type2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(SimpleEnum.Zwei)]
    [global::System.Runtime.Serialization.DataMember(Name=@"type2", Order = 45, IsRequired = false)]
    
    public SimpleEnum Type2
    {
      get { return _type2; }
      set { _type2 = value; }
    }
    private VerySimple _msg = null;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    [global::System.Runtime.Serialization.DataMember(Name=@"msg", Order = 33, IsRequired = false)]
    
    public VerySimple Msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private readonly global::System.Collections.Generic.List<VerySimple> _list = new global::System.Collections.Generic.List<VerySimple>();
    [global::ProtoBuf.ProtoMember(34, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.Runtime.Serialization.DataMember(Name=@"list", Order = 34, IsRequired = false)]
    
    public global::System.Collections.Generic.List<VerySimple> List
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"verySimple")]
  [global::System.Runtime.Serialization.DataContract(Name=@"verySimple")]
  public partial class VerySimple : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"inMsg")]
  [global::System.Runtime.Serialization.DataContract(Name=@"inMsg")]
  public partial class InMsg : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"outMsg")]
  [global::System.Runtime.Serialization.DataContract(Name=@"outMsg")]
  public partial class OutMsg : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"simpleEnum")]
    [global::System.Runtime.Serialization.DataContract(Name=@"simpleEnum")]
    public enum SimpleEnum
    {
      
      [global::ProtoBuf.ProtoEnum(Name=@"eins", Value=1)]
      [global::System.Runtime.Serialization.EnumMember(Value=@"eins")]
      Eins = 1,
      
      [global::ProtoBuf.ProtoEnum(Name=@"zwei", Value=2)]
      [global::System.Runtime.Serialization.EnumMember(Value=@"zwei")]
      Zwei = 2
    }
  
    [global::System.ServiceModel.ServiceContract(Name = @"simpleService1")]
    public interface ISimpleService1
    {
      
        [global::System.ServiceModel.OperationContract(Name = @"s1")]
        [global::ProtoBuf.ServiceModel.ProtoBehavior]
        OutMsg S1(InMsg request);
    
        [global::System.ServiceModel.OperationContract(AsyncPattern = true, Name = @"s1")]
        global::System.IAsyncResult BeginS1(InMsg request, global::System.AsyncCallback callback, object state);
    OutMsg EndS1(global::System.IAsyncResult ar);
    
        [global::System.ServiceModel.OperationContract(Name = @"s11")]
        [global::ProtoBuf.ServiceModel.ProtoBehavior]
        SimpleMessage S11(SimpleMessage request);
    
        [global::System.ServiceModel.OperationContract(AsyncPattern = true, Name = @"s11")]
        global::System.IAsyncResult BeginS11(SimpleMessage request, global::System.AsyncCallback callback, object state);
    SimpleMessage EndS11(global::System.IAsyncResult ar);
    
    }

    public partial class S1CompletedEventArgs : global::System.ComponentModel.AsyncCompletedEventArgs
    {
        private readonly object[] results;

        public S1CompletedEventArgs(object[] results, global::System.Exception exception, bool cancelled, object userState)
            : base(exception, cancelled, userState) 
        {
            this.results = results;
        }
        
        public OutMsg Result
        {
            get { 
                base.RaiseExceptionIfNecessary();
                return (OutMsg)(this.results[0]);
            }
        }
    }
  

    public partial class S11CompletedEventArgs : global::System.ComponentModel.AsyncCompletedEventArgs
    {
        private readonly object[] results;

        public S11CompletedEventArgs(object[] results, global::System.Exception exception, bool cancelled, object userState)
            : base(exception, cancelled, userState) 
        {
            this.results = results;
        }
        
        public SimpleMessage Result
        {
            get { 
                base.RaiseExceptionIfNecessary();
                return (SimpleMessage)(this.results[0]);
            }
        }
    }
  
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class SimpleService1Client : global::System.ServiceModel.ClientBase<ISimpleService1>, ISimpleService1
    {
        public SimpleService1Client()
        {}
        public SimpleService1Client(string endpointConfigurationName) 
            : base(endpointConfigurationName) 
        {}
        public SimpleService1Client(string endpointConfigurationName, string remoteAddress) 
            : base(endpointConfigurationName, remoteAddress)
        {}
        public SimpleService1Client(string endpointConfigurationName, global::System.ServiceModel.EndpointAddress remoteAddress)
            : base(endpointConfigurationName, remoteAddress)
        {}
        public SimpleService1Client(global::System.ServiceModel.Channels.Binding binding, global::System.ServiceModel.EndpointAddress remoteAddress)
            : base(binding, remoteAddress)
        {}

        
        private BeginOperationDelegate onBeginS1Delegate;
        private EndOperationDelegate onEndS1Delegate;
        private global::System.Threading.SendOrPostCallback onS1CompletedDelegate;

        public event global::System.EventHandler<S1CompletedEventArgs> S1Completed;

        public OutMsg S1(InMsg request)
        {
            return base.Channel.S1(request);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.IAsyncResult BeginS1(InMsg request, global::System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginS1(request, callback, asyncState);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public OutMsg EndS1(global::System.IAsyncResult result)
        {
            return base.Channel.EndS1(result);
        }

        private global::System.IAsyncResult OnBeginS1(object[] inValues, global::System.AsyncCallback callback, object asyncState)
        {
            InMsg request = ((InMsg)(inValues[0]));
            return this.BeginS1(request, callback, asyncState);
        }

        private object[] OnEndS1(global::System.IAsyncResult result)
        {
            OutMsg retVal = this.EndS1(result);
            return new object[] {
                retVal};
        }

        private void OnS1Completed(object state)
        {
            if ((this.S1Completed != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.S1Completed(this, new S1CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void S1Async(InMsg request)
        {
            this.S1Async(request, null);
        }

        public void S1Async(InMsg request, object userState)
        {
            if ((this.onBeginS1Delegate == null))
            {
                this.onBeginS1Delegate = new BeginOperationDelegate(this.OnBeginS1);
            }
            if ((this.onEndS1Delegate == null))
            {
                this.onEndS1Delegate = new EndOperationDelegate(this.OnEndS1);
            }
            if ((this.onS1CompletedDelegate == null))
            {
                this.onS1CompletedDelegate = new global::System.Threading.SendOrPostCallback(this.OnS1Completed);
            }
            base.InvokeAsync(this.onBeginS1Delegate, new object[] {
                    request}, this.onEndS1Delegate, this.onS1CompletedDelegate, userState);
        }
    
        private BeginOperationDelegate onBeginS11Delegate;
        private EndOperationDelegate onEndS11Delegate;
        private global::System.Threading.SendOrPostCallback onS11CompletedDelegate;

        public event global::System.EventHandler<S11CompletedEventArgs> S11Completed;

        public SimpleMessage S11(SimpleMessage request)
        {
            return base.Channel.S11(request);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.IAsyncResult BeginS11(SimpleMessage request, global::System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginS11(request, callback, asyncState);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public SimpleMessage EndS11(global::System.IAsyncResult result)
        {
            return base.Channel.EndS11(result);
        }

        private global::System.IAsyncResult OnBeginS11(object[] inValues, global::System.AsyncCallback callback, object asyncState)
        {
            SimpleMessage request = ((SimpleMessage)(inValues[0]));
            return this.BeginS11(request, callback, asyncState);
        }

        private object[] OnEndS11(global::System.IAsyncResult result)
        {
            SimpleMessage retVal = this.EndS11(result);
            return new object[] {
                retVal};
        }

        private void OnS11Completed(object state)
        {
            if ((this.S11Completed != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.S11Completed(this, new S11CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void S11Async(SimpleMessage request)
        {
            this.S11Async(request, null);
        }

        public void S11Async(SimpleMessage request, object userState)
        {
            if ((this.onBeginS11Delegate == null))
            {
                this.onBeginS11Delegate = new BeginOperationDelegate(this.OnBeginS11);
            }
            if ((this.onEndS11Delegate == null))
            {
                this.onEndS11Delegate = new EndOperationDelegate(this.OnEndS11);
            }
            if ((this.onS11CompletedDelegate == null))
            {
                this.onS11CompletedDelegate = new global::System.Threading.SendOrPostCallback(this.OnS11Completed);
            }
            base.InvokeAsync(this.onBeginS11Delegate, new object[] {
                    request}, this.onEndS11Delegate, this.onS11CompletedDelegate, userState);
        }
    
    }
  
    [global::System.ServiceModel.ServiceContract(Name = @"simpleService2")]
    public interface ISimpleService2
    {
      
        [global::System.ServiceModel.OperationContract(Name = @"s2")]
        [global::ProtoBuf.ServiceModel.ProtoBehavior]
        SimpleMessage S2(SimpleMessage request);
    
        [global::System.ServiceModel.OperationContract(AsyncPattern = true, Name = @"s2")]
        global::System.IAsyncResult BeginS2(SimpleMessage request, global::System.AsyncCallback callback, object state);
    SimpleMessage EndS2(global::System.IAsyncResult ar);
    
    }

    public partial class S2CompletedEventArgs : global::System.ComponentModel.AsyncCompletedEventArgs
    {
        private readonly object[] results;

        public S2CompletedEventArgs(object[] results, global::System.Exception exception, bool cancelled, object userState)
            : base(exception, cancelled, userState) 
        {
            this.results = results;
        }
        
        public SimpleMessage Result
        {
            get { 
                base.RaiseExceptionIfNecessary();
                return (SimpleMessage)(this.results[0]);
            }
        }
    }
  
    [global::System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class SimpleService2Client : global::System.ServiceModel.ClientBase<ISimpleService2>, ISimpleService2
    {
        public SimpleService2Client()
        {}
        public SimpleService2Client(string endpointConfigurationName) 
            : base(endpointConfigurationName) 
        {}
        public SimpleService2Client(string endpointConfigurationName, string remoteAddress) 
            : base(endpointConfigurationName, remoteAddress)
        {}
        public SimpleService2Client(string endpointConfigurationName, global::System.ServiceModel.EndpointAddress remoteAddress)
            : base(endpointConfigurationName, remoteAddress)
        {}
        public SimpleService2Client(global::System.ServiceModel.Channels.Binding binding, global::System.ServiceModel.EndpointAddress remoteAddress)
            : base(binding, remoteAddress)
        {}

        
        private BeginOperationDelegate onBeginS2Delegate;
        private EndOperationDelegate onEndS2Delegate;
        private global::System.Threading.SendOrPostCallback onS2CompletedDelegate;

        public event global::System.EventHandler<S2CompletedEventArgs> S2Completed;

        public SimpleMessage S2(SimpleMessage request)
        {
            return base.Channel.S2(request);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.IAsyncResult BeginS2(SimpleMessage request, global::System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginS2(request, callback, asyncState);
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public SimpleMessage EndS2(global::System.IAsyncResult result)
        {
            return base.Channel.EndS2(result);
        }

        private global::System.IAsyncResult OnBeginS2(object[] inValues, global::System.AsyncCallback callback, object asyncState)
        {
            SimpleMessage request = ((SimpleMessage)(inValues[0]));
            return this.BeginS2(request, callback, asyncState);
        }

        private object[] OnEndS2(global::System.IAsyncResult result)
        {
            SimpleMessage retVal = this.EndS2(result);
            return new object[] {
                retVal};
        }

        private void OnS2Completed(object state)
        {
            if ((this.S2Completed != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.S2Completed(this, new S2CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void S2Async(SimpleMessage request)
        {
            this.S2Async(request, null);
        }

        public void S2Async(SimpleMessage request, object userState)
        {
            if ((this.onBeginS2Delegate == null))
            {
                this.onBeginS2Delegate = new BeginOperationDelegate(this.OnBeginS2);
            }
            if ((this.onEndS2Delegate == null))
            {
                this.onEndS2Delegate = new EndOperationDelegate(this.OnEndS2);
            }
            if ((this.onS2CompletedDelegate == null))
            {
                this.onS2CompletedDelegate = new global::System.Threading.SendOrPostCallback(this.OnS2Completed);
            }
            base.InvokeAsync(this.onBeginS2Delegate, new object[] {
                    request}, this.onEndS2Delegate, this.onS2CompletedDelegate, userState);
        }
    
    }
  
}
