// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

// Generated from: Test.proto
// Note: requires additional types generated from: descriptor.proto
namespace foo.bar
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MyMessage")]
  public partial class MyMessage : global::ProtoBuf.IExtensible
  {
    public MyMessage() {}

    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FooOptions")]
  public partial class FooOptions : global::ProtoBuf.IExtensible
  {
    public FooOptions() {}

    private int _opt1 = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"opt1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int opt1
    {
      get { return _opt1; }
      set { _opt1 = value; }
    }
    private string _opt2 = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"opt2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string opt2
    {
      get { return _opt2; }
      set { _opt2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Bar")]
  public partial class Bar : global::ProtoBuf.IExtensible
  {
    public Bar() {}

    private int _a = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"a", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int a
    {
      get { return _a; }
      set { _a = value; }
    }
    private int _b = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"b", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int b
    {
      get { return _b; }
      set { _b = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Foo")]
  public partial class Foo : global::ProtoBuf.IExtensible
  {
    public Foo() {}

    private int _bar = default(int);
    [global::ProtoBuf.ProtoMember(126, IsRequired = false, Name=@"bar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bar
    {
      get { return _bar; }
      set { _bar = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"simpleMessage1")]
  public partial class simpleMessage1 : global::ProtoBuf.IExtensible
  {
    public simpleMessage1() {}

    private int _i1_int32_test = default(int);
    [global::System.Obsolete, global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"i1_int32_test", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int i1_int32_test
    {
      get { return _i1_int32_test; }
      set { _i1_int32_test = value; }
    }
    private int _i2 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"i2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int i2
    {
      get { return _i2; }
      set { _i2 = value; }
    }
    private string _s1_string = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"s1_string", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string s1_string
    {
      get { return _s1_string; }
      set { _s1_string = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _i3_3d = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"i3_3d", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> i3_3d
    {
      get { return _i3_3d; }
    }
  
    private foo.bar.simpleEnum _type = foo.bar.simpleEnum.zwei;
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(foo.bar.simpleEnum.zwei)]
    public foo.bar.simpleEnum type
    {
      get { return _type; }
      set { _type = value; }
    }
    private foo.bar.simpleEnum _type2 = foo.bar.simpleEnum.zwei;
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"type2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(foo.bar.simpleEnum.zwei)]
    public foo.bar.simpleEnum type2
    {
      get { return _type2; }
      set { _type2 = value; }
    }
    private foo.bar.verySimple _msg = null;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public foo.bar.verySimple msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private readonly global::System.Collections.Generic.List<foo.bar.verySimple> _list = new global::System.Collections.Generic.List<foo.bar.verySimple>();
    [global::ProtoBuf.ProtoMember(34, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<foo.bar.verySimple> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"verySimple")]
  public partial class verySimple : global::ProtoBuf.IExtensible
  {
    public verySimple() {}

    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"inMsg1")]
  public partial class inMsg1 : global::ProtoBuf.IExtensible
  {
    public inMsg1() {}

    private foo.bar.inMsg1.Corpus _corpus = foo.bar.inMsg1.Corpus.UNIVERSAL;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"corpus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(foo.bar.inMsg1.Corpus.UNIVERSAL)]
    public foo.bar.inMsg1.Corpus corpus
    {
      get { return _corpus; }
      set { _corpus = value; }
    }
    private foo.bar.outMsg2 _msg2 = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msg2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public foo.bar.outMsg2 msg2
    {
      get { return _msg2; }
      set { _msg2 = value; }
    }
    private foo.bar.inMsg1.outMsg1 _msg1 = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msg1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public foo.bar.inMsg1.outMsg1 msg1
    {
      get { return _msg1; }
      set { _msg1 = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"outMsg1")]
  public partial class outMsg1 : global::ProtoBuf.IExtensible
  {
    public outMsg1() {}

    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Corpus")]
    public enum Corpus
    {
      
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSAL", Value=0)]
      UNIVERSAL = 0,
      
      [global::ProtoBuf.ProtoEnum(Name=@"WEB", Value=1)]
      WEB = 1,
      
      [global::ProtoBuf.ProtoEnum(Name=@"IMAGES", Value=2)]
      IMAGES = 2,
      
      [global::ProtoBuf.ProtoEnum(Name=@"LOCAL", Value=3)]
      LOCAL = 3,
      
      [global::ProtoBuf.ProtoEnum(Name=@"NEWS", Value=4)]
      NEWS = 4,
      
      [global::ProtoBuf.ProtoEnum(Name=@"PRODUCTS", Value=5)]
      PRODUCTS = 5,
      
      [global::ProtoBuf.ProtoEnum(Name=@"VIDEO", Value=6)]
      VIDEO = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"outMsg2")]
  public partial class outMsg2 : global::ProtoBuf.IExtensible
  {
    public outMsg2() {}

    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"test3")]
  public partial class test3 : global::ProtoBuf.IExtensible
  {
    public test3() {}

    private foo.bar.test10.test11 _test = null;
    [global::System.Obsolete, global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"test", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public foo.bar.test10.test11 test
    {
      get { return _test; }
      set { _test = value; }
    }
    private string _testex = "";
    [global::ProtoBuf.ProtoMember(12345, IsRequired = false, Name=@"testex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string testex
    {
      get { return _testex; }
      set { _testex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"test2")]
  public partial class test2 : global::ProtoBuf.IExtensible
  {
    public test2() {}

    private readonly global::System.Collections.Generic.List<int> _field1 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(33, Name=@"field1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> field1
    {
      get { return _field1; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _field2 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"field2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> field2
    {
      get { return _field2; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"test10")]
  public partial class test10 : global::ProtoBuf.IExtensible
  {
    public test10() {}

    private int _field1 = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"field1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int field1
    {
      get { return _field1; }
      set { _field1 = value; }
    }
    private string _field2 = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"field2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string field2
    {
      get { return _field2; }
      set { _field2 = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _fields = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(33, Name=@"fields", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> fields
    {
      get { return _fields; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"test11")]
  public partial class test11 : global::ProtoBuf.IExtensible
  {
    public test11() {}

    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"enum11")]
    public enum enum11
    {
      
      [global::ProtoBuf.ProtoEnum(Name=@"test1", Value=1)]
      test1 = 1,
      
      [global::ProtoBuf.ProtoEnum(Name=@"test2", Value=2)]
      test2 = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"allTypes")]
  public partial class allTypes : global::ProtoBuf.IExtensible
  {
    public allTypes() {}

    private double _doublef = default(double);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"doublef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double doublef
    {
      get { return _doublef; }
      set { _doublef = value; }
    }
    private float _floatf = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"floatf", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float floatf
    {
      get { return _floatf; }
      set { _floatf = value; }
    }
    private long _int64f = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"int64f", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long int64f
    {
      get { return _int64f; }
      set { _int64f = value; }
    }
    private ulong _uint64f = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"uint64f", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uint64f
    {
      get { return _uint64f; }
      set { _uint64f = value; }
    }
    private int _int32f = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"int32f", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int int32f
    {
      get { return _int32f; }
      set { _int32f = value; }
    }
    private ulong _fixed64f = default(ulong);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fixed64f", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong fixed64f
    {
      get { return _fixed64f; }
      set { _fixed64f = value; }
    }
    private uint _fixed32f = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fixed32f", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fixed32f
    {
      get { return _fixed32f; }
      set { _fixed32f = value; }
    }
    private bool _boolf = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"boolf", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool boolf
    {
      get { return _boolf; }
      set { _boolf = value; }
    }
    private string _stringf = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"stringf", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stringf
    {
      get { return _stringf; }
      set { _stringf = value; }
    }
    private byte[] _bytesf = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"bytesf", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] bytesf
    {
      get { return _bytesf; }
      set { _bytesf = value; }
    }
    private uint _uint32f = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"uint32f", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uint32f
    {
      get { return _uint32f; }
      set { _uint32f = value; }
    }
    private int _sfixed32f = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"sfixed32f", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sfixed32f
    {
      get { return _sfixed32f; }
      set { _sfixed32f = value; }
    }
    private long _sfixed64f = default(long);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"sfixed64f", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sfixed64f
    {
      get { return _sfixed64f; }
      set { _sfixed64f = value; }
    }
    private int _sint32f = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"sint32f", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sint32f
    {
      get { return _sint32f; }
      set { _sint32f = value; }
    }
    private long _sint64f = default(long);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"sint64f", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sint64f
    {
      get { return _sint64f; }
      set { _sint64f = value; }
    }
    private foo.bar.testenum1 _enumf = foo.bar.testenum1.enum2;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"enumf", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(foo.bar.testenum1.enum2)]
    public foo.bar.testenum1 enumf
    {
      get { return _enumf; }
      set { _enumf = value; }
    }
    private foo.bar.test1 _messagef = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"messagef", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public foo.bar.test1 messagef
    {
      get { return _messagef; }
      set { _messagef = value; }
    }
    private bool _boolf2 = (bool)true;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"boolf2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)true)]
    public bool boolf2
    {
      get { return _boolf2; }
      set { _boolf2 = value; }
    }
    private int _int32f2 = (int)123;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"int32f2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)123)]
    public int int32f2
    {
      get { return _int32f2; }
      set { _int32f2 = value; }
    }
    private string _stringf2 = @"lkjlkj";
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"stringf2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"lkjlkj")]
    public string stringf2
    {
      get { return _stringf2; }
      set { _stringf2 = value; }
    }
    private byte[] _bytesf2 =  /* 
        1,2,3
        */ null ;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"bytesf2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue( /* 
        1,2,3
        */ null )]
    public byte[] bytesf2
    {
      get { return _bytesf2; }
      set { _bytesf2 = value; }
    }
    private foo.bar.testenum1 _enumf2 = foo.bar.testenum1.enum1;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"enumf2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(foo.bar.testenum1.enum1)]
    public foo.bar.testenum1 enumf2
    {
      get { return _enumf2; }
      set { _enumf2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"test1")]
  public partial class test1 : global::ProtoBuf.IExtensible
  {
    public test1() {}

    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"simpleEnum")]
    public enum simpleEnum
    {
      
      [global::ProtoBuf.ProtoEnum(Name=@"eins", Value=1)]
      eins = 1,
      
      [global::ProtoBuf.ProtoEnum(Name=@"zwei", Value=2)]
      zwei = 2,
      
      [global::ProtoBuf.ProtoEnum(Name=@"drei", Value=3)]
      drei = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"testenum1")]
    public enum testenum1
    {
      
      [global::ProtoBuf.ProtoEnum(Name=@"enum1", Value=1)]
      enum1 = 1,
      
      [global::ProtoBuf.ProtoEnum(Name=@"enum2", Value=12)]
      enum2 = 12
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"testenum2")]
    public enum testenum2
    {
      
      [global::ProtoBuf.ProtoEnum(Name=@"enum3", Value=1)]
      enum3 = 1,
      
      [global::ProtoBuf.ProtoEnum(Name=@"enum4", Value=12)]
      enum4 = 12,
      
      [global::ProtoBuf.ProtoEnum(Name=@"enum5", Value=12)]
      enum5 = 12
    }
  
    public interface IsimpleService3
    {
      foo.bar.outMsg2 s21(foo.bar.inMsg1 request);
    foo.bar.simpleMessage1 s211(foo.bar.simpleMessage1 request);
    
    }
    public interface IsimpleService4
    {
      foo.bar.simpleMessage1 s22(foo.bar.simpleMessage1 request);
    
    }
    public interface Iservice1
    {
      foo.bar.test2 serv1(foo.bar.test1 request);
    foo.bar.test1 serv2(foo.bar.test2 request);
    
    }
}
