//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Test2.proto
namespace MichaelReukauff.Lexer
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"test2")]
  public partial class test2 : global::ProtoBuf.IExtensible
  {
    public test2() {}
    
    private string _t1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"t1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string t1
    {
      get { return _t1; }
      set { _t1 = value; }
    }

    private string _t2 = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"t2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string t2
    {
      get { return _t2; }
      set { _t2 = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _t3 = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"t3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> t3
    {
      get { return _t3; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
