// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

// Generated from: Options.proto
// Note: requires additional types generated from: descriptor.proto
namespace MichaelReukauff.Lexer.Protobufs
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MyMessage")]
  public partial class MyMessage : global::ProtoBuf.IExtensible
  {
    public MyMessage() {}

    private int _foo = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"foo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int foo
    {
      get { return _foo; }
      set { _foo = value; }
    }
    private string _bar = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bar
    {
      get { return _bar; }
      set { _bar = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestType")]
  public partial class RequestType : global::ProtoBuf.IExtensible
  {
    public RequestType() {}

    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseType")]
  public partial class ResponseType : global::ProtoBuf.IExtensible
  {
    public ResponseType() {}

    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MyEnum")]
    public enum MyEnum
    {
      
      [global::ProtoBuf.ProtoEnum(Name=@"FOO", Value=1)]
      FOO = 1,
      
      [global::ProtoBuf.ProtoEnum(Name=@"BAR", Value=2)]
      BAR = 2
    }
  
    public interface IMyService
    {
      ResponseType MyMethod(RequestType request);
    
    }
}
